### ISSUE TITLE
Timer start From Its Initial Value every time i click on Button or Any Event 

### ISSUE THREAD

**Issue by akashjai95** [avid21/react-native-timer-countdown#7]
> this.setState({
            time:7200
        })

> clearResponse=()=>{
        this.setState({clear:1})
    }

> 
    render(){
      
            return(
                <View style={{flex:1}}>
                    <TimerCountdown initialSecondsRemaining={this.state.time*1000} style={{fontSize:20, marginLeft:5, color:'white'}}/>
                    <View>
                        <Button onPress={this.clearResponse}>
                            <Text>Clear</Text>
                        </Button>
                    </View>
                </View>
            )

**Comment by mtx62** [comment]
I'm having the same issue

**Comment by avid21** [comment]
I recommend using this component as props so that it cannot be affected by state changes.

**Comment by avid21** [comment]
PRs to improve this repo are always welcome!

**Comment by iRayan7** [comment]
@avid21 could you please elaborate on using the component as props?

**Comment by avid21** [comment]
Simply like this: @iRayan7 
`
render(){
        return(
            <A renderTimerCountdown={()=><TimerCountdown/>}/>
        );
}
`

**Comment by avid21** [comment]
@iRayan7, @akashjai95, @ssilverr, @mtx62 
I'm planning to update readme with faq for this. Any feedback?

**Comment by noelyoo** [comment]
import React, { Component } from 'react';
import { StyleSheet, Button, View } from 'react-native';
import TimerCountdown from 'react-native-timer-countdown';

export default class A extends Component {
  render() {
    return (
      <View style={styles.container}>
        <B renderTimer={() => <Timer />} />
      </View>
    );
  }
}

class B extends Component {
  state = { isPressed: false }
  render() {
    return (
      <View styles={{ flex: 1 }}>
        {this.props.renderTimer()}
        <Button
          title={`${this.state.isPressed ? 'Button Pressed' : 'Button'}`}
          onPress={() => { this.setState({ isPressed: true }) }}
        />
      </View >
    )
  }
}

const Timer = () => (
  <TimerCountdown
    initialSecondsRemaining={60000}
    onTick={secondsRemaining => console.log('tick', secondsRemaining)}
    onTimeElapsed={() => console.log('complete')}
    allowFontScaling={true}
    style={{ fontSize: 20 }}
  />
);


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by noelyoo** [comment]
README updated:
https://github.com/noelyoo/react-native-timer-countdown/commit/187fc2373fe25755d7371b9d7b337d4ee0746c8d
